Miniapps MFEM Parallel

diff --git a/.github/workflows/sanitizers.yml b/.github/workflows/sanitizers.yml
--- a/.github/workflows/sanitizers.yml
+++ b/.github/workflows/sanitizers.yml
@@ -1042,8 +1042,84 @@ jobs:
               MFEM_INSTALL_DIR=${GITHUB_WORKSPACE}/mfem-install make all -j $(nproc); \
               MFEM_INSTALL_DIR=${GITHUB_WORKSPACE}/mfem-install make test || { echo "Tests in $${dir} failed!"; exit 1; };
           EOF
+          make
 
-# Miniapps tests MFEM Parallel with Sanitizers
+  ########################
+  # Miniapps MFEM Parallel
+  # Cache:   cache-miniapps-par-${{matrix.sanitizer}}
+  # Upload: upload-miniapps-par-${{matrix.sanitizer}}
+  test-par-miniapps:
+    needs: [test-par-check]
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        sanitizer: [asan, ubsan]
+    name: test-par-miniapps-${{matrix.sanitizer}}
+    steps:
+      - name: Cache
+        id: cache-par-miniapps
+        uses: actions/cache@v4
+        with:
+          path: mfem-install
+          key: cache-miniapps-par-${{matrix.sanitizer}}
+      - name: Setup
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        run: |
+          echo LLVM_DIR=${GITHUB_WORKSPACE}/llvm >> $GITHUB_ENV
+          echo LSAN_OPTIONS="suppressions=${GITHUB_WORKSPACE}/${{env.LSAN_DIR}}/${{env.LSAN_FILE}}" >> $GITHUB_ENV
+      - name: Setup (LLVM_LIB)
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        run: echo LLVM_LIB=${LLVM_DIR}/lib >> $GITHUB_ENV
+      - name: Setup (LLVM_LDFLAGS)
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        run: echo "LLVM_LDFLAGS=-L${{env.LLVM_LIB}} -lc++abi -Wl,-rpath,${{env.LLVM_LIB}}" >> $GITHUB_ENV
+      - name: Restore MFEM
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        id: mfem-cache
+        uses: actions/cache@v4
+        with:
+          path: mfem-install
+          fail-on-cache-miss: true
+          key: cache-mfem-par-${{matrix.sanitizer}}
+      - name: Patch config.mk
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        run: sed -i -e '/^MFEM_LIBS/ s/$/ $(LLVM_LDFLAGS)/' mfem-install/share/mfem/config.mk
+      - name: Restore LLVM libcxx
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        uses: actions/cache@v4
+        with:
+          path: ${{env.LLVM_DIR}}
+          fail-on-cache-miss: true
+          key: cache-llvm-${{env.LLVM_VER}}-${{matrix.sanitizer}}
+      - name: Restore LSAN file
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        uses: actions/cache@v4
+        with:
+          path: ${{env.LSAN_DIR}}
+          fail-on-cache-miss: true
+          key: cache-lsan-suppression-file
+      - name: Checkout
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        uses: actions/checkout@v4
+        with:
+          path: mfem
+          ref: ubsan
+          repository: mfem/mfem  # 🔥🔥🔥 Using MFEM/ubsan repository
+      - name: Makefile
+        working-directory: mfem/miniapps
+        if: steps.cache-par-miniapps.outputs.cache-hit != 'true'
+        run: |
+          cat << EOF > makefile
+          MINIAPP_DIRS := $(shell find . -type d -maxdepth 1 -not -path .)
+          MINIAPP_TEST_DIRS := $(filter-out %/common,$(MINIAPP_DIRS))
+          test-miniapps:
+            for dir in $(MINIAPP_TEST_DIRS); do \
+              echo "Running tests in $${dir} ..."; \
+              MFEM_INSTALL_DIR=${GITHUB_WORKSPACE}/mfem-install make all -j $(nproc); \
+              MFEM_INSTALL_DIR=${GITHUB_WORKSPACE}/mfem-install make test || { echo "Tests in $${dir} failed!"; exit 1; };
+          EOF
+          make
 
 # Split unit tests into separate files with:
 # ./unit_tests --filenames-as-tags --list-tags|grep '\[#' | cut -d '[' -f 2 | cut -d']' -f1 > tests
